#!/usr/bin/env bash
# Install NGINX web server

apt-get update
apt-get -y install nginx
# Allow nginx access through firewall
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
