#!/usr/bin/env bash
# This script Installs, configures, and starts the server
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html

ufw allow 'Nginx HTTP'
rdrct='server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sed -i "s|server_name\s*_;|$rdrct|" /etc/nginx/sites-available/default
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart