#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt update
sudo apt install nginx -y
sudo sed -i "20i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
