#!/usr/bin/env bash
# configure web-02 to be identical to web-01

apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
    add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	location /redirect_me {
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
    error_page 404 /404.html;
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi