#!/usr/bin/env bash
# This script installs and sets up HAproxy.

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 239507-web-01 54.87.212.104:80 check
    server 239507-web-02 100.25.156.57:80 check
"
apt-get -y update
apt-get -y upgrade
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
