#!/bin/bash

# Author: Samuel Martins
# Date Created: 20/02/2023
# Last Modified: 20/02/2023

# Description:
# This script backs up the alx-system_engineering-devops directory
# and then moves it to a different directory for safe keeping

# usage:
# ./backup

zip -r alx-sys-devops.zip ~/alx-course/alx-system_engineering-devops
# the zip command is used to create the archive
# the -r flag is used to recursively include all files and subdirectories within
# alx-sys-devops.zip is the name of the resulting zip

mv alx-sys-devops.zip ~/Documents/zipped/
# the mv command is responsible for moving the zip to a destination folder "zipped"

exit 0
